version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres-attendance
    ports:
      - "6601:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_system
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-attendance
    ports:
      - "3041:3041"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: attendance_system
      PORT: 3041
    command: sh -c "sleep 10 && node server.js"
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: frontend-attendance
    ports:
      - "8138:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr:
    build: ./HR
    container_name: hr-attendance
    ports:
      - "8139:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

